version: '3.8'

networks:
  main:
    name: minitwit-networks

services:
  minitwit-db:
    image: mongo:latest
    command: [--auth]
    environment:
      MONGO_INITDB_ROOT_USERNAME: minitwit
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - minitwit-db_data:/data/db
    ports:
      - '27018:27017'
    networks:
      - main
    secrets:
      - db_password

  minitwit-backend:
    image: minitwit-backend
    build:
      context: .
      dockerfile: MiniTwit.Server/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:5001;http://+:5000
      # ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      # ASPNETCORE_Kestrel__Certificates__Default__Password: localhost
      ConnectionStrings__MiniTwit:
      JwtSettings__Key:
    ports:
      - '5000:5000'
      - '5001:5001'
    networks:
      - main
    # volumes:
    #   - '~/.aspnet/https/:/https/'
    depends_on:
      - minitwit-db
    secrets:
      - source: connection_string
        target: ConnectionStrings__MiniTwit
      - source: jwt_key
        target: JwtSettings__Key

  minitwit-frontend:
    image: minitwit-frontend
    build:
      context: .
      dockerfile: MiniTwit.Web/Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    networks:
      - main
    depends_on:
      - minitwit-backend

volumes:
  minitwit-db_data:

secrets:
  db_password:
    file: '.local/db_password.txt'
  connection_string:
    file: '.local/connection_string.txt'
  jwt_key:
    file: '.local/jwt_key.txt'