name: Build & Test
on:
  push:

jobs:
  Backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

  Frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: MiniTwit.Web
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.x
          cache: 'npm'
          cache-dependency-path: MiniTwit.Web/package-lock.json
      
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      # - name: Test
      #   run: echo Not implemented