name: Code Analysis
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
  actions: read          # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
  contents: read         # for actions/checkout to fetch code

jobs:
  CodeQL:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/Checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
            languages: csharp

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  Snyk:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Snyk CLI
        uses: snyk/actions/setup@master

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore Backend dependencies
        run: dotnet restore

      - name: Run Snyk Static Code Analysis
        run: snyk code test --report --org=${{ secrets.SNYK_ORG_ID }} --sarif > snyk-code.sarif || true

      - name: Run Snyk Open Source Monitor
        run: snyk monitor --all-projects --org=${{ secrets.SNYK_ORG_ID }}
      
      - name: Run Snyk IaC tests and report
        run: snyk iac test --report --org=${{ secrets.SNYK_ORG_ID }} || true
      
      - name: Build MiniTwit Backend Docker image
        run: docker build -t miniTwit-backend:latest -f MiniTwit.Server/Dockerfile .

      # - name: Build MiniTwit Frontend Docker image
      #   run: docker build -t miniTwit-frontend:latest -f MiniTwit.Web/Dockerfile .
      
      - name: Run Snyk Container Monitor on MiniTwit Backend
        run: snyk container monitor --org=${{ secrets.SNYK_ORG_ID }} miniTwit-backend:latest --file=MiniTwit.Server/Dockerfile

      # - name: Run Snyk Container Monitor on MiniTwit Frontend
      #   run: snyk container monitor --org=${{ secrets.SNYK_ORG_ID }} MiniTwit-Frontend:latest --file=MiniTwit.Web/Dockerfile

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-code.sarif