name: Docker Image
on:
  push:
    branches: [main]

jobs:
  build-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push MiniTwit Backend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: MiniTwit.Server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/minitwit-backend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/minitwit-backend:serverbuildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/minitwit-backend:serverbuildcache,mode=max

      - name: Build and push MiniTwit Frontend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: MiniTwit.Web/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/minitwit-frontend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/minitwit-frontend:webbuildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/minitwit-frontend:webbuildcache,mode=max